### ISSUE TITLE
This issue is a todo list

### ISSUE THREAD

**Issue by Kritiqual** [Kritiqual/Neovim#1]
Here is something need improvement
- [ ] Rewrite, modulize init.lua
- [ ] Automate packer. plugin installation
- [ ] Configure LSP, autocompletetion
- [ ] Configure keybinding (with which-key ?)]
- [ ] Configure dashboard
- [ ] Configure debug
- [ ] Some other stuff
